Repository codenteq/imtihan, pull requests merged in 2022-10, with the labels that each got.

#8 Database schema edited
  backend/app/Models/ClassRoom.php
  backend/app/Models/Company.php
  backend/app/Models/Meeting.php
  backend/app/Models/NotificationUser.php
  backend/app/Models/PaymentPackage.php
  backend/app/Models/PaymentPlan.php
  backend/app/Models/Support.php
  backend/app/Models/User.php
  backend/app/Models/UserInfo.php
  backend/composer.lock
  backend/database/factories/UserFactory.php
  backend/database/factories/UserInfoFactory.php
  backend/database/migrations/2014_10_12_000000_create_users_table.php
  backend/database/migrations/2022_09_14_195752_create_user_infos_table.php
  backend/database/migrations/2022_09_14_200201_create_companies_table.php
  backend/database/migrations/2022_09_14_200658_create_countries_table.php
  backend/database/migrations/2022_09_14_200708_create_cities_table.php
  backend/database/migrations/2022_09_14_200718_create_states_table.php
  backend/database/migrations/2022_09_14_201013_create_payment_plans_table.php
  backend/database/migrations/2022_09_14_201112_create_payment_packages_table.php
  backend/database/migrations/2022_09_14_202127_create_months_table.php
  backend/database/migrations/2022_09_28_183934_create_meetings_table.php
  backend/database/migrations/2022_09_28_193018_create_class_rooms_table.php
Labels: help wanted, edited

#9 Meeting changed Booking and Model, Migrations edited.
  backend/app/Models/Booking.php
  backend/app/Models/BookingSetting.php
  backend/composer.lock
  backend/database/migrations/2022_09_28_183934_create_bookings_table.php
  backend/database/migrations/2022_09_28_184419_create_booking_settings_table.php
Labels: wontfix, edited

#11 Migrations new feature added
  backend/database/migrations/2014_10_12_000000_create_users_table.php
  backend/database/migrations/2019_08_19_000000_create_failed_jobs_table.php
  backend/database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
  backend/database/migrations/2022_09_14_195752_create_user_infos_table.php
  backend/database/migrations/2022_09_14_200201_create_companies_table.php
  backend/database/migrations/2022_09_14_200658_create_countries_table.php
  backend/database/migrations/2022_09_14_200708_create_cities_table.php
  backend/database/migrations/2022_09_14_200718_create_states_table.php
  backend/database/migrations/2022_09_14_201653_create_payment_methods_table.php
  backend/database/migrations/2022_09_14_201947_create_payment_coupons_table.php
  backend/database/migrations/2022_09_14_202236_create_supports_table.php
  backend/database/migrations/2022_09_14_202434_create_notifications_table.php
  backend/database/migrations/2022_09_14_202627_create_notification_device_tokens_table.php
  backend/database/migrations/2022_09_14_202638_create_notification_users_table.php
  backend/database/migrations/2022_09_28_183934_create_bookings_table.php
  backend/database/migrations/2022_09_28_184419_create_booking_settings_table.php
  backend/database/migrations/2022_09_28_193018_create_class_rooms_table.php
  backend/database/migrations/2022_09_28_194045_create_live_lessons_table.php
  backend/database/migrations/2022_10_01_190022_create_questions_table.php
  backend/database/migrations/2022_10_01_191519_create_question_categories_table.php
  backend/database/migrations/2022_10_01_192030_create_question_options_table.php
  backend/database/migrations/2022_10_01_193058_create_languages_table.php
  backend/database/migrations/2022_10_01_231340_create_exam_user_answers_table.php
Labels: enhancement, edited

#13 Migrations uuid changed default id
  backend/database/migrations/2014_10_12_000000_create_users_table.php
  backend/database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
  backend/database/migrations/2022_09_14_195752_create_user_infos_table.php
  backend/database/migrations/2022_09_14_200201_create_companies_table.php
  backend/database/migrations/2022_09_14_200658_create_countries_table.php
  backend/database/migrations/2022_09_14_200708_create_cities_table.php
  backend/database/migrations/2022_09_14_200718_create_states_table.php
  backend/database/migrations/2022_09_14_201653_create_payment_methods_table.php
  backend/database/migrations/2022_09_14_201947_create_payment_coupons_table.php
  backend/database/migrations/2022_09_14_202236_create_supports_table.php
  backend/database/migrations/2022_09_14_202434_create_notifications_table.php
  backend/database/migrations/2022_09_14_202627_create_notification_device_tokens_table.php
  backend/database/migrations/2022_09_14_202638_create_notification_users_table.php
  backend/database/migrations/2022_09_28_183934_create_bookings_table.php
  backend/database/migrations/2022_09_28_184419_create_booking_settings_table.php
  backend/database/migrations/2022_09_28_185431_create_class_exams_table.php
  backend/database/migrations/2022_09_28_193018_create_class_rooms_table.php
  backend/database/migrations/2022_09_28_194045_create_live_lessons_table.php
  backend/database/migrations/2022_10_01_190022_create_questions_table.php
  backend/database/migrations/2022_10_01_191519_create_question_categories_table.php
  backend/database/migrations/2022_10_01_192030_create_question_options_table.php
  backend/database/migrations/2022_10_01_193058_create_languages_table.php
  backend/database/migrations/2022_10_01_193533_create_question_bugs_table.php
  backend/database/migrations/2022_10_01_194934_create_exams_table.php
  backend/database/migrations/2022_10_01_225224_create_exam_questions_table.php
  backend/database/migrations/2022_10_01_225734_create_exam_results_table.php
  backend/database/migrations/2022_10_01_230528_create_exam_result_categories_table.php
  backend/database/migrations/2022_10_01_231340_create_exam_user_answers_table.php
  backend/database/migrations/2022_10_01_232315_create_question_by_companies_table.php
  backend/database/migrations/2022_10_01_233307_create_class_exam_categories_table.php
  backend/database/migrations/2022_10_01_234950_create_lessons_table.php
  backend/database/migrations/2022_10_02_001636_create_payment_settings_table.php
  backend/database/migrations/2022_10_02_002530_create_invoices_table.php
  backend/database/migrations/2022_10_08_154356_create_conditions_table.php
  backend/database/migrations/2022_10_08_155153_create_condition_categories_table.php
Labels: edited

#14 Migrations, Models, Factories edited.
  backend/app/Models/Booking.php
  backend/app/Models/ClassExam.php
  backend/app/Models/Company.php
  backend/app/Models/Condition.php
  backend/app/Models/Language.php
  backend/app/Models/Notification.php
  backend/app/Models/PaymentMethod.php
  backend/app/Models/Support.php
  backend/app/Models/UserInfo.php
  backend/database/factories/CompanyFactory.php
  backend/database/factories/UserInfoFactory.php
  backend/database/migrations/2022_09_14_195752_create_user_infos_table.php
  backend/database/migrations/2022_09_14_200201_create_companies_table.php
  backend/database/migrations/2022_09_14_201653_create_payment_methods_table.php
  backend/database/migrations/2022_09_14_202236_create_supports_table.php
  backend/database/migrations/2022_09_14_202434_create_notifications_table.php
  backend/database/migrations/2022_09_28_183934_create_bookings_table.php
  backend/database/migrations/2022_09_28_185431_create_class_exams_table.php
  backend/database/migrations/2022_10_01_193058_create_languages_table.php
  backend/database/migrations/2022_10_08_154356_create_conditions_table.php
Labels: edited

#15 Factories added.
  backend/app/Models/Booking.php
  backend/app/Models/ClassExam.php
  backend/app/Models/Language.php
  backend/database/factories/BookingFactory.php
  backend/database/factories/BookingSettingFactory.php
  backend/database/factories/ClassExamCategoryFactory.php
  backend/database/factories/ClassExamFactory.php
  backend/database/factories/LanguageFactory.php
Labels: enhancement, edited

#16 New factories added
  backend/app/Models/Condition.php
  backend/app/Models/Notification.php
  backend/app/Models/PaymentMethod.php
  backend/app/Models/PaymentSetting.php
  backend/app/Models/Question.php
  backend/app/Models/QuestionOption.php
  backend/app/Models/Support.php
  backend/database/factories/ClassRoomFactory.php
  backend/database/factories/ConditionCategoryFactory.php
  backend/database/factories/ConditionFactory.php
  backend/database/factories/ExamFactory.php
  backend/database/factories/ExamQuestionFactory.php
  backend/database/factories/ExamResultCategoryFactory.php
  backend/database/factories/ExamResultFactory.php
  backend/database/factories/ExamUserAnswerFactory.php
  backend/database/factories/InvoiceFactory.php
  backend/database/factories/LessonFactory.php
  backend/database/factories/LiveLessonFactory.php
  backend/database/factories/NotificationDeviceTokenFactory.php
  backend/database/factories/NotificationFactory.php
  backend/database/factories/NotificationUserFactory.php
  backend/database/factories/PaymentCouponFactory.php
  backend/database/factories/PaymentMethodFactory.php
  backend/database/factories/PaymentSettingFactory.php
  backend/database/factories/QuestionBugFactory.php
  backend/database/factories/QuestionByCompanyFactory.php
  backend/database/factories/QuestionCategoryFactory.php
  backend/database/factories/QuestionFactory.php
  backend/database/factories/QuestionOptionFactory.php
  backend/database/factories/SupportFactory.php
Labels: enhancement, edited

#17 Admin language api added
  backend/.env.testing
  backend/app/Http/Controllers/Admin/LanguageController.php
  backend/app/Http/Requests/Admin/Language/LanguageStoreRequest.php
  backend/app/Http/Requests/Admin/Language/LanguageUpdateRequest.php
  backend/app/Http/Resources/Admin/LanguageResource.php
  backend/app/Services/Admin/CarTypeService.php
  backend/app/Services/Admin/CompanyInfoService.php
  backend/app/Services/Admin/CompanyService.php
  backend/app/Services/Admin/CouponService.php
  backend/app/Services/Admin/GroupService.php
  backend/app/Services/Admin/InvoiceService.php
  backend/app/Services/Admin/LanguageService.php
  backend/app/Services/Admin/LessonContentService.php
  backend/app/Services/Admin/PackageService.php
  backend/app/Services/Admin/PaymentPlanService.php
  backend/app/Services/Admin/PeriodService.php
  backend/app/Services/Admin/QuestionService.php
  backend/app/Services/Admin/QuestionTypeService.php
  backend/app/Services/Base/BaseService.php
  backend/app/Services/FirebaseNotificationService.php
  backend/app/Services/GlobalService.php
  backend/app/Services/ImageConvertService.php
  backend/app/Services/InvoiceCreatorService.php
  backend/app/Services/Manager/AppointmentService.php
  backend/app/Services/Manager/CarService.php
  backend/app/Services/Manager/ClassExamService.php
  backend/app/Services/Manager/CompanyService.php
  backend/app/Services/Manager/LiveLessonService.php
  backend/app/Services/Manager/NotificationService.php
  backend/app/Services/Manager/QuestionService.php
  backend/app/Services/Payment/PayService.php
  backend/app/Services/QuizService.php
  backend/app/Services/TestResult/TestResultService.php
  backend/app/Services/TestResult/TestResultTypeService.php
  backend/app/Services/ThirdPartyService/SendPortalService.php
  backend/app/Services/User/AppointmentService.php
  backend/routes/api.php
  backend/tests/Feature/Admin/LanguageControllerTest.php
  backend/tests/Feature/CompanyTest.php
  backend/tests/Feature/UserInfoTest.php
Labels: enhancement, API

#18 Github Action Added
  .github/workflows/laravel.yml
Labels: enhancement

#20 Issue Template, Funding, Pull Request Template added.
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/1_Bug_report.md
  .github/ISSUE_TEMPLATE/2_Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENCE
  README.md
  SECURITY.md
  backend/README.md
Labels: feature request, documents

#21 Update LINCESE changed name
  LICENSE
Labels: edited

#22 Bug fix and Error handling added
  backend/app/Exceptions/Handler.php
  backend/app/Helpers/Helper.php
  backend/app/Http/Controllers/API/Admin/LanguageController.php
  backend/app/Http/Controllers/API/ApiController.php
  backend/app/Http/Controllers/Admin/LanguageController.php
  backend/app/Http/Resources/Admin/LanguageResource.php
  backend/app/Jobs/ImageConvertJob.php
  backend/app/Jobs/NotificationJob.php
  backend/app/Jobs/TestResultJob.php
  backend/app/Models/Booking.php
  backend/app/Models/BookingSetting.php
  backend/app/Models/ClassExam.php
  backend/app/Models/ClassRoom.php
  backend/app/Models/Company.php
  backend/app/Models/Condition.php
  backend/app/Models/ConditionCategory.php
  backend/app/Models/Language.php
  backend/app/Models/LiveLesson.php
  backend/app/Models/Notification.php
  backend/app/Models/NotificationDeviceToken.php
  backend/app/Models/NotificationUser.php
  backend/app/Models/PaymentCoupon.php
  backend/app/Models/PaymentMethod.php
  backend/app/Models/PaymentSetting.php
  backend/app/Models/Question.php
  backend/app/Models/QuestionOption.php
  backend/app/Models/Support.php
  backend/app/Models/User.php
  backend/app/Models/UserInfo.php
  backend/app/Services/Base/BaseService.php
  backend/app/Traits/ApiResponser.php
  backend/database/factories/UserInfoFactory.php
  backend/database/migrations/2022_09_14_195752_create_user_infos_table.php
  backend/database/migrations/2022_09_14_200201_create_companies_table.php
  backend/database/migrations/2022_09_14_200708_create_cities_table.php
  backend/routes/api.php
  backend/tests/Feature/Admin/LanguageControllerTest.php
Labels: enhancement, bug fixed

#23 changed apiResources
  backend/routes/api.php
Labels: edited

#33 bug fixed
  backend/app/Exceptions/Handler.php
  backend/app/Traits/ApiResponser.php
  backend/docker-compose.yml
  backend/docker/8.1/supervisord.conf
  backend/package-lock.json
  backend/package.json
Labels: bug

#35 Bugs fix
  backend/app/Exceptions/Handler.php
  backend/routes/api.php
  backend/tests/Feature/Admin/LanguageControllerTest.php
Labels: bug

#37 Condition configuration added
  backend/app/Exceptions/Handler.php
  backend/app/Http/Controllers/API/Admin/Condition/ConditionCategoryController.php
  backend/app/Http/Controllers/API/Admin/Condition/ConditionController.php
  backend/app/Http/Controllers/API/Admin/LanguageController.php
  backend/app/Http/Requests/Admin/Condition/StoreConditionCategoryRequest.php
  backend/app/Http/Requests/Admin/Condition/StoreConditionRequest.php
  backend/app/Http/Requests/Admin/Condition/UpdateConditionCategoryRequest.php
  backend/app/Http/Requests/Admin/Condition/UpdateConditionRequest.php
  backend/app/Http/Requests/Admin/Language/StoreLanguageRequest.php
  backend/app/Http/Requests/Admin/Language/UpdateLanguageRequest.php
  backend/app/Http/Resources/Admin/Condition/ConditionCategoryResource.php
  backend/app/Http/Resources/Admin/Condition/ConditionResource.php
  backend/app/Models/ConditionCategory.php
  backend/app/Services/Admin/Condition/ConditionCategoryService.php
  backend/app/Services/Admin/Condition/ConditionService.php
  backend/app/Traits/ApiResponser.php
  backend/database/factories/ConditionCategoryFactory.php
  backend/database/factories/ConditionFactory.php
  backend/database/factories/QuestionCategoryFactory.php
  backend/routes/api.php
  backend/tests/Feature/Admin/Condition/ConditionCategoryControllerTest.php
  backend/tests/Feature/Admin/Condition/ConditionControllerTest.php
Labels: enhancement, API, bug fixed, conflicts, backend

#36 API call added
  backend/app/Http/Controllers/API/Admin/ClassRoomController.php
  backend/app/Http/Controllers/API/Admin/Payment/PaymentCouponController.php
  backend/app/Http/Controllers/API/Admin/Payment/PaymentMethodController.php
  backend/app/Http/Controllers/API/Admin/Payment/PaymentSettingController.php
  backend/app/Http/Requests/Admin/ClassRoom/StoreClassRoomRequest.php
  backend/app/Http/Requests/Admin/ClassRoom/UpdateClassRoomRequest.php
  backend/app/Http/Requests/Admin/Payment/StorePaymentCouponRequest.php
  backend/app/Http/Requests/Admin/Payment/StorePaymentMethodRequest.php
  backend/app/Http/Requests/Admin/Payment/StorePaymentSettingRequest.php
  backend/app/Http/Requests/Admin/Payment/UpdatePaymentCouponRequest.php
  backend/app/Http/Requests/Admin/Payment/UpdatePaymentMethodRequest.php
  backend/app/Http/Requests/Admin/Payment/UpdatePaymentSettingRequest.php
  backend/app/Http/Resources/Admin/ClassRoomResource.php
  backend/app/Http/Resources/Admin/Payment/PaymentCouponResource.php
  backend/app/Http/Resources/Admin/Payment/PaymentMethodResource.php
  backend/app/Http/Resources/Admin/Payment/PaymentSettingResource.php
  backend/app/Services/Admin/ClassRoomService.php
  backend/app/Services/Admin/Payment/PaymentCouponService.php
  backend/app/Services/Admin/Payment/PaymentMethodService.php
  backend/app/Services/Admin/Payment/PaymentSettingService.php
  backend/database/factories/PaymentSettingFactory.php
  backend/routes/api.php
  backend/tests/Feature/Admin/ClassRoomControllerTest.php
  backend/tests/Feature/Admin/Payment/PaymentCouponControllerTest.php
  backend/tests/Feature/Admin/Payment/PaymentMethodControllerTest.php
  backend/tests/Feature/Admin/Payment/PaymentSettingControllerTest.php
Labels: enhancement, edited, API, conflicts, backend

#38 linter done.
  backend/routes/api.php
Labels: linter

#39 API call aded and edited factories under the company.
  backend/app/Http/Controllers/API/Admin/Post/AnnouncementController.php
  backend/app/Http/Controllers/API/Admin/Post/SliderController.php
  backend/app/Http/Requests/Admin/Post/StoreAnnouncementRequest.php
  backend/app/Http/Requests/Admin/Post/StoreSliderRequest.php
  backend/app/Http/Requests/Admin/Post/UpdateAnnouncementRequest.php
  backend/app/Http/Requests/Admin/Post/UpdateSliderRequest.php
  backend/app/Http/Resources/Admin/Post/AnnouncementResource.php
  backend/app/Http/Resources/Admin/Post/SliderResource.php
  backend/app/Models/Announcement.php
  backend/app/Models/Slider.php
  backend/app/Services/Admin/Post/AnnouncementService.php
  backend/app/Services/Admin/Post/SliderService.php
  backend/database/factories/AnnouncementFactory.php
  backend/database/factories/CityFactory.php
  backend/database/factories/CompanyFactory.php
  backend/database/factories/CountryFactory.php
  backend/database/factories/SliderFactory.php
  backend/database/factories/StateFactory.php
  backend/database/migrations/2022_10_22_203134_create_announcements_table.php
  backend/database/migrations/2022_10_22_230014_create_sliders_table.php
  backend/routes/api.php
  backend/tests/Feature/Admin/Post/AnnouncementControllerTest.php
  backend/tests/Feature/Admin/Post/SliderControllerTest.php
Labels: enhancement, edited, API, backend

#40 Added question api call
  .github/workflows/laravel.yml
  backend/app/Exceptions/Handler.php
  backend/app/Http/Controllers/API/Admin/LanguageController.php
  backend/app/Http/Controllers/API/Admin/Question/QuestionCatergoryController.php
  backend/app/Http/Controllers/API/Admin/Question/QuestionController.php
  backend/app/Http/Requests/Admin/Question/StoreQuestionCategoryRequest.php
  backend/app/Http/Requests/Admin/Question/StoreQuestionRequest.php
  backend/app/Http/Requests/Admin/Question/UpdateQuestionCategoryRequest.php
  backend/app/Http/Requests/Admin/Question/UpdateQuestionRequest.php
  backend/app/Http/Resources/Admin/Question/QuestionCategoryResource.php
  backend/app/Http/Resources/Admin/Question/QuestionOptionResource.php
  backend/app/Http/Resources/Admin/Question/QuestionResource.php
  backend/app/Models/Question.php
  backend/app/Models/QuestionCategory.php
  backend/app/Models/QuestionOption.php
  backend/app/Services/Admin/Question/QuestionCategoryService.php
  backend/app/Services/Admin/Question/QuestionService.php
  backend/app/Services/Base/BaseService.php
  backend/database/factories/QuestionFactory.php
  backend/database/factories/QuestionOptionFactory.php
  backend/database/migrations/2022_10_01_190022_create_questions_table.php
  backend/database/migrations/2022_10_01_192030_create_question_options_table.php
  backend/routes/api.php
  backend/tests/Feature/Admin/Question/QuestionCategoryControllerTest.php
  backend/tests/Feature/Admin/Question/QuestionControllerTest.php
Labels: API, conflicts, backend, linter

#41 API call added.
  backend/app/Http/Controllers/API/Admin/CompanyController.php
  backend/app/Http/Controllers/API/Manager/Booking/BookingController.php
  backend/app/Http/Controllers/API/Manager/Booking/BookingSettingController.php
  backend/app/Http/Requests/Admin/Company/StoreCompanyRequest.php
  backend/app/Http/Requests/Admin/Company/UpdateCompanyRequest.php
  backend/app/Http/Requests/Manager/Booking/StoreBookingRequest.php
  backend/app/Http/Requests/Manager/Booking/StoreBookingSettingRequest.php
  backend/app/Http/Requests/Manager/Booking/UpdateBookingRequest.php
  backend/app/Http/Requests/Manager/Booking/UpdateBookingSettingRequest.php
  backend/app/Http/Resources/Admin/CompanyResource.php
  backend/app/Http/Resources/Manager/Booking/BookingResource.php
  backend/app/Http/Resources/Manager/Booking/BookingSettingResource.php
  backend/app/Services/Admin/CompanyService.php
  backend/app/Services/Manager/Booking/BookingService.php
  backend/app/Services/Manager/Booking/BookingSettingService.php
  backend/composer.lock
  backend/database/factories/CompanyFactory.php
  backend/routes/api.php
  backend/tests/Feature/Admin/CompanyControllerTest.php
  backend/tests/Feature/Manager/Booking/BookingControllerTest.php
  backend/tests/Feature/Manager/Booking/BookingSettingControllerTest.php
Labels: enhancement, edited, API, bug fixed, Test, backend
